schema = 1
name = "catppuccin"
displayName = "Catppuccin"

[tokens]
"bg.canvas" = "#11111b"
"bg.surface" = "#11111b"
"bg.elevated" = "#313244"
"fg.primary" = "#cdd6f4"
"fg.secondary" = "#a6adc8"
"fg.muted" = "#7f849c"
"border.subtle" = "#313244"
"border.strong" = "#45475a"
"accent" = "#cba6f7"
"cursor" = "#f5e0dc"
"cursor.text" = "#11111b"
"selection.bg" = "#45475a"
"selection.fg" = "#ffffff"
"ansi.black" = "#45475a"
"ansi.red" = "#f38ba8"
"ansi.green" = "#a6e3a1"
"ansi.yellow" = "#f9e2af"
"ansi.blue" = "#89b4fa"
"ansi.magenta" = "#f5c2e7"
"ansi.cyan" = "#94e2d5"
"ansi.white" = "#bac2de"
"ansi.brightBlack" = "#585b70"
"ansi.brightRed" = "#f38ba8"
"ansi.brightGreen" = "#a6e3a1"
"ansi.brightYellow" = "#f9e2af"
"ansi.brightBlue" = "#89b4fa"
"ansi.brightMagenta" = "#f5c2e7"
"ansi.brightCyan" = "#94e2d5"
"ansi.brightWhite" = "#a6adc8"
