schema = 1
name = "solarized-dark"
displayName = "Solarized Dark"

[tokens]
"bg.canvas" = "#002b36"
"bg.surface" = "#002b36"
"bg.elevated" = "#0d3d49"
"fg.primary" = "#839496"
"fg.secondary" = "#93a1a1"
"fg.muted" = "#657b83"
"border.subtle" = "#12404b"
"border.strong" = "#2aa198"
"accent" = "#268bd2"
"cursor" = "#93a1a1"
"cursor.text" = "#002b36"
"selection.bg" = "#073642"
"selection.fg" = "#eee8d5"
"ansi.black" = "#073642"
"ansi.red" = "#dc322f"
"ansi.green" = "#859900"
"ansi.yellow" = "#b58900"
"ansi.blue" = "#268bd2"
"ansi.magenta" = "#d33682"
"ansi.cyan" = "#2aa198"
"ansi.white" = "#eee8d5"
"ansi.brightBlack" = "#002b36"
"ansi.brightRed" = "#cb4b16"
"ansi.brightGreen" = "#586e75"
"ansi.brightYellow" = "#657b83"
"ansi.brightBlue" = "#839496"
"ansi.brightMagenta" = "#6c71c4"
"ansi.brightCyan" = "#93a1a1"
"ansi.brightWhite" = "#fdf6e3"
