schema = 1
name = "tokyo-night"
displayName = "Tokyo Night"

[tokens]
"bg.canvas" = "#16161e"
"bg.surface" = "#16161e"
"bg.elevated" = "#1a1b26"
"fg.primary" = "#a9b1d6"
"fg.secondary" = "#787c99"
"fg.muted" = "#515670"
"border.subtle" = "#292e42"
"border.strong" = "#3d59a1"
"accent" = "#7aa2f7"
"cursor" = "#c0caf5"
"cursor.text" = "#16161e"
"selection.bg" = "#1c1d29"
"selection.fg" = "#c0caf5"
"ansi.black" = "#363b54"
"ansi.red" = "#f7768e"
"ansi.green" = "#73daca"
"ansi.yellow" = "#e0af68"
"ansi.blue" = "#7aa2f7"
"ansi.magenta" = "#bb9af7"
"ansi.cyan" = "#7dcfff"
"ansi.white" = "#787c99"
"ansi.brightBlack" = "#363b54"
"ansi.brightRed" = "#f7768e"
"ansi.brightGreen" = "#73daca"
"ansi.brightYellow" = "#e0af68"
"ansi.brightBlue" = "#7aa2f7"
"ansi.brightMagenta" = "#bb9af7"
"ansi.brightCyan" = "#7dcfff"
"ansi.brightWhite" = "#acb0d0"
